name: Deploy Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'documentation/public/wiki/**'
  workflow_dispatch:

jobs:
  deploy-wiki:
    if: github.repository == 'Anexgohan/pankha'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: documentation/public/wiki
          commit-message: "Auto-update from main repo documentation/public/wiki"
